<?php

/**
 * @file
 * Module containing custom oda code.
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\views\ViewExecutable;
use Drupal\Core\Link;

/**
 * Implements hook_page_attachments() to add library oda.node_page to
 * data_report node type..
 *
 * @param array<string, mixed> $attachments
 */
function oda_page_attachments(array &$attachments): void {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    if ($node->getType() == 'data_report') {
      $attachments['#attached']['library'][] = 'oda/node_page';
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array<string, mixed> $form
 */
function oda_form_views_exposed_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state): void {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $form_state->get('view');
  if ($view->id() == 'oda_data' && $view->current_display == 'page_1') {
    $form['#action'] .= '#edit-search-api-fulltext--2';
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * @param array<string, mixed> $attachments
 */
function oda_page_attachments_alter(array &$attachments): void {
  $domain = \Drupal::service('oit.domain')->getDomain();
  if ($domain == 'oda') {
    $google_site_verify = [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'google-site-verification',
        'content' => 'sdDO7pnhCwXnZiU7VRq4lFwoo0TsvpyUUbcYq6s-9A4',
      ],
    ];
    $attachments['#attached']['html_head'][] = [$google_site_verify, 'google-site-verification'];
  }
}

/**
 * Implements hook_views_pre_render().
 */
function oda_views_pre_view(ViewExecutable $view): void {
  if ($view->id() == 'oda_data') {
    // Get current users roles.
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();

    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('oda_access_control');

    $oda_access_terms = [];
    foreach ($terms as $term) {
      $tid = $term->tid;
      $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);

      $query = \Drupal::database()->select('permissions_by_term_role', 't');
      $query->condition('t.tid', $tid);
      $query->fields('t', ['tid', 'rid']);
      $results = $query->execute()->fetchAll();

      $oda_access_terms[$tid] = $results;
    }

    $view_filters = $view->display_handler->getOption('filters');
    $view_filters['field_oda_report_access']['value'] = [];
    foreach ($oda_access_terms as $term_role_list) {
      foreach ($term_role_list as $term_role_part) {
        $term_role = $term_role_part->rid;
        $term_tid = $term_role_part->tid;

        // If term role is 'administrator', 'authenticated', 'pseudo_admin', or 'anonymous' then continue.
        if ($term_role == 'administrator' || $term_role == 'anonymous' || $term_role == 'authenticated' || $term_role == 'pseudo_admin'|| $term_role == 'oda_super_editors') {
          continue;
        }
        if (in_array('administrator', $roles) || in_array('pseudo_admin', $roles) || in_array('oda_super_editors', $roles)) {
          $view_filters['field_oda_report_access']['value'][$term_tid] = $term_tid;
        }
        elseif (in_array($term_role, $roles)) {
          $view_filters['field_oda_report_access']['value'][$term_tid] = $term_tid;
        }
      }
    }

    if (empty($view_filters['field_oda_report_access']['value'])) {
      $view_filters['field_oda_report_access']['value'][1228] = 1228;
    }

    $view->display_handler->setOption('filters', $view_filters);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function oda_views_pre_render(ViewExecutable $view): void {
  if ($view->id() == 'oda_data') {
    $view->element['#attached']['library'][] = 'oda/data_report_layout';
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array<string, mixed> $form
 */
function oda_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $domain = \Drupal::service('oit.domain')->getDomain();
  if ($domain == 'oda') {
    oit_set_domain_defaults($form, 'oda', 'oda_colorado_edu');
  }

  if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-media-media-page-list") {
    if ($domain == 'oda') {
      $options = [];
      foreach ($form['type']['#options'] as $key => $value) {
        if ($key == 'oda_files' || $key == 'oda_images') {
          $options[$key] = $value;
        }
      }
      $form['type']['#options'] = $options;
    }
  }

  if ($form['#id'] == 'views-exposed-form-moderated-content-moderated-content') {
    if ($domain == 'oda') {
      $form['#attached']['library'][] = 'oda/admin_content';
      _oit_form_set_domain('content/moderated', 'oda_colorado_edu');
    }
  }

  // Add custom library to admin content page and set domain.
  if ($form_id == "views_form_content_page_1") {
    $domain = \Drupal::service('oit.domain')->getDomain();
    if ($domain == 'oda') {
      $form['#attached']['library'][] = 'oda/admin_content';
      _oit_form_set_domain('content', 'oda_colorado_edu');
    }
  }

  if ($form_id == "search_block_form") {
    $domain = \Drupal::service('oit.domain')->getDomain();
    if ($domain == 'oda') {
      $form['keys']['#attributes']['placeholder'] = t('Search Site');
    }
  }

  if ($form_id == "node_webform_form" || $form_id == "node_webform_edit_form") {
    $domain = \Drupal::service('oit.domain')->getDomain();
    if ($domain == 'oda') {
      $form['field_oit_category']['#access'] = FALSE;
    }
  }

  // Set defaults on new data report nodes.
  if ($form_id == "node_data_report_form") {
    $form['body']['widget'][0]['#default_value'] = '<p>ODA Data Report Info</p><p><strong>Tags:</strong> tag, tag, tag</p>';
  }

  // Set defaults on data report nodes for ODA type.
  if ($form_id == "node_data_report_form" || $form_id == "node_data_report_edit_form") {
    $form['#attached']['library'][] = 'webform/webform.element.select2';
    $form['#attached']['library'][] = 'oda/oit_data_report_page_form';
    // Group for access report TAC.
    $form['oda_access_group'] = [
      '#title' => t('Data Report Access Group'),
      '#type' => 'details',
      '#group' => 'advanced',
      '#open' => 1,
      '#weight' => 99,
    ];
    $form['field_oda_report_access']['#group'] = 'oda_access_group';
    // Group for page sub-type extra fields.
    $form['oda_terms'] = [
      '#title' => t('Terms'),
      '#type' => 'details',
      '#group' => 'advanced',
      '#open' => 1,
      '#weight' => 100,
    ];
    $form['field_oda_population']['#group'] = 'oda_terms';
    $form['field_oda_level_of_detail']['#group'] = 'oda_terms';
    $form['field_oda_cu_stats']['#group'] = 'oda_terms';
    $form['field_oda_course_data']['#group'] = 'oda_terms';
    $form['field_oda_term']['#group'] = 'oda_terms';
    $form['field_oda_type']['#group'] = 'oda_terms';
    $form['field_oda_academic_terms_covered']['#group'] = 'oda_terms';
    $form['field_oda_demographics']['#group'] = 'oda_terms';
    $form['field_oda_peers_ext_org']['#group'] = 'oda_terms';
    $form['field_oda_financial']['#group'] = 'oda_terms';
    $form['field_oda_surveys']['#group'] = 'oda_terms';


    // if current user is 'oda_super_editors' or 'administrator'.
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if (in_array('oda_super_editors', $roles) || in_array('administrator', $roles)) {
      // Add 'Add/Delete Terms' button to taxonomy fields.
      $term_list = [
        'oda_population',
        'oda_level_of_detail',
        'oda_cu_stats',
        'oda_course_data',
        'oda_term',
        'oda_type',
        'oda_academic_terms_covered',
        'oda_demographics',
        'oda_peers_ext_org',
      ];
      foreach ($term_list as $term) {
        $link = oda_term_edit($term);
        $form_term = 'field_' . $term;
        $form[$form_term]['widget']['#suffix'] = $link;
      }
    }
  }

  // Set defaults on data page nodes for ODA type.
  if ($form_id == "node_oda_page_form" || $form_id == "node_oda_page_edit_form") {
    $advanced = [
      '#type' => 'inline_template',
      '#template' => '<details>
      <summary>{{ details_title }}</summary>
      <ul>
        <li>
          <a href="{{ svg_link }}" class="edit-button use-ajax" data-dialog-type="dialog" data-dialog-renderer="off_canvas" data-dialog-options="{&quot;width&quot;:400}">
            {{ svg_title }}
          </a>
        </li>
      </ul>
      </details>',
      '#context' => [
        'details_title' => t('advanced html'),
        'svg_link' => '/admin/config/content/shortcode_svg/svg_list',
        'svg_title' => t('Icons shortcode panel'),
      ],
      '#weight' => 13,
      '#allowed_tags' => [
        'button',
        'details',
        'summary',
        'ul',
        'li',
        'a',
        'p',
        'h3',
      ],
    ];
    $form['oit_advanced'] = $advanced;
  }

}

/**
 * Set domain on content to match site domain
 *
 * @param array<string, mixed> $form
 */
function _oda_set_oda_domain(array &$form, FormStateInterface $form_state): void {
  _oit_set_domain_submit($form, $form_state, 'oda', 'oda_colorado_edu');
}

/**
 * Create term edit links.
 */
function oda_term_edit(string $term_id, string $edit_label = 'Add/Delete Terms'): string {
  $url = Url::fromUri("internal:/admin/structure/taxonomy/manage/$term_id/overview");
  $link = Link::fromTextAndUrl(t($edit_label), $url);

  return $link->toString()->getGeneratedLink();
}

/**
 * Implements hook_shortcut_default_set().
 */
function oda_shortcut_default_set(): ?string {
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();

  // if roles array contains 'oda_editors' or 'oda_super_editors'.
  if (in_array('oda_editors', $roles)) {
      return 'oda';
  }
  if (in_array('oda_super_editors', $roles)) {
      return 'oda-super-editor';
  }
  return NULL;
}

